# Generated by Django 3.1.2 on 2020-11-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_categorya_categoryb_categoryc'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='desc',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
