# Generated by Django 3.1.2 on 2020-11-04 22:21

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=auctions.models.upload_to)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='auctions.listing')),
            ],
        ),
    ]
