# Generated by Django 3.1.2 on 2020-11-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201104_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
