# Generated by Django 3.1.2 on 2020-11-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='status',
            new_name='is_active',
        ),
    ]
