# Generated by Django 3.1.2 on 2020-11-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201110_0004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'listing', 'date_added')},
        ),
    ]
